const actionTypes = {
    // Cart Actions
    FETCH_CART_REQUEST: 'FETCH_CART_REQUEST',
    FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS',
    FETCH_CART_FAILURE: 'FETCH_CART_FAILURE',

    ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',

    UPDATE_CART_ITEM_REQUEST: 'UPDATE_CART_ITEM_REQUEST',
    UPDATE_CART_ITEM_SUCCESS: 'UPDATE_CART_ITEM_SUCCESS',
    UPDATE_CART_ITEM_FAILURE: 'UPDATE_CART_ITEM_FAILURE',

    REMOVE_FROM_CART_REQUEST: 'REMOVE_FROM_CART_REQUEST',
    REMOVE_FROM_CART_SUCCESS: 'REMOVE_FROM_CART_SUCCESS',
    REMOVE_FROM_CART_FAILURE: 'REMOVE_FROM_CART_FAILURE',

    CLEAR_CART_REQUEST: 'CLEAR_CART_REQUEST',
    CLEAR_CART_SUCCESS: 'CLEAR_CART_SUCCESS',
    CLEAR_CART_FAILURE: 'CLEAR_CART_FAILURE',
    
    TOGGLE_CART_DISPLAY: 'TOGGLE_CART_DISPLAY',
  
    // Auth Actions
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    CHECK_AUTH_STATUS: 'CHECK_AUTH_STATUS',
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
  
    // Orders Actions
    FETCH_ORDERS_REQUEST: 'FETCH_ORDERS_REQUEST',
    FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_FAILURE: 'FETCH_ORDERS_FAILURE',
    FETCH_ORDER_DETAILS_REQUEST: 'FETCH_ORDER_DETAILS_REQUEST',
    FETCH_ORDER_DETAILS_SUCCESS: 'FETCH_ORDER_DETAILS_SUCCESS',
    FETCH_ORDER_DETAILS_FAILURE: 'FETCH_ORDER_DETAILS_FAILURE',
    CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST',
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',
  
    // Products Actions
    FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
    FETCH_PRODUCT_DETAILS_REQUEST: 'FETCH_PRODUCT_DETAILS_REQUEST',
    FETCH_PRODUCT_DETAILS_SUCCESS: 'FETCH_PRODUCT_DETAILS_SUCCESS',
    FETCH_PRODUCT_DETAILS_FAILURE: 'FETCH_PRODUCT_DETAILS_FAILURE',
    SEARCH_PRODUCTS_REQUEST: 'SEARCH_PRODUCTS_REQUEST',
    SEARCH_PRODUCTS_SUCCESS: 'SEARCH_PRODUCTS_SUCCESS',
    SEARCH_PRODUCTS_FAILURE: 'SEARCH_PRODUCTS_FAILURE',
  };
  
  export default actionTypes;
  