export { default as CartPage } from '../pages/cart/CartPage';
export { default as OrdersPage } from '../pages/orders/OrdersPage';
export { default as OrderDetailPage } from './order-details/OrderDetailPage';
export { default as ProductDetailPage } from './product-details/ProductDetailPage';
export { default as CheckoutPage } from '../pages/checkout/CheckoutPage';
export { default as HomePage } from './home/HomePage';
export { default as ProductsPage } from '../pages/products/ProductsPage';
export { default as LoginPage } from '../pages/login/LoginPage';
export { default as RegisterPage } from '../pages/register/RegisterPage';