export { default as CartPage } from './cart/CartPage';
export { default as OrdersPage } from './orders/OrdersPage';
export { default as OrderDetailPage } from './order-details/OrderDetailPage';
export { default as ProductDetailPage } from './product-details/ProductDetailPage';
export { default as CheckoutPage } from './checkout/CheckoutPage';
export { default as HomePage } from './home/HomePage';
export { default as ProductsPage } from './products/ProductsPage';
export { default as LoginPage } from './login/LoginPage';
export { default as RegisterPage } from './register/RegisterPage';